### PR TITLE
fix: rename then to andThen

### LINKED ISSUE #2751: Addition of 'then' function in 0.26.0 makes Ramda an incomplete thenable
Code to replicate:

```js
const R = require("ramda");
(async function() {
  return await R;
})();
// (node:46376) UnhandledPromiseRejectionWarning:
// TypeError: `then` expected a Promise, received function () { [native code] }
```

We’re running into this issue with Observable, in which we `await` library loads from dynamic `import()` calls, but it’ll also happen for anyone who’s using the `esm` module to do dynamic import() in Node.js now, and for anyone who uses Node.js dynamic import whenever they ship it. Here’s the dynamic import failure case:

```js
(async function() {
  const R = await import("ramda/es/index.js");
})().catch(e => console.error(e));
// TypeError: `then` expected a Promise, received function () { [native code] }
// at _assertPromise (/Users/tmcw/tmp/a/node_modules/ramda/es/internal/_assertPromise.js:6:11)
```

This code works properly in `0.25.0` and breaks in `0.26.0` and beyond, because `await` works like:

1. Await the imported code
2. Await the result of that import

Before, because Ramda was an object, the second await didn't do anything. Now, because it's a 'thenable object' - an object with a then method - `await` tries to await its eventual value and triggers the error.

---

I'm not a maintainer or contributor of this project, so my 2c on how to resolve this is likely to miss something - my only real guess for a solution would be to rename `then` to something else.

### PR DESCRIPTION
**Pull request by tmcw**
BREAKING CHANGE

The addition of R.then in Ramda 0.26 made the R object
a Promise-like object, and meant that Promise.resolve() will attempt
to resolve it by calling the then() method. R is not a Promise, and
to reassure JavaScript of this fact, R.then is renamed to R.andThen.

Fixes #2751

### CODE REVIEW

File: source/andThen.js [hunk 1]
```diff
@@ -14,7 +14,7 @@ import _assertPromise from './internal/_assertPromise';
  * @sig (a -> (Promise e b)) -> (Promise e a) -> (Promise e b)
  * @param {Function} onSuccess The function to apply. Can return a value or a promise of a value.
  * @param {Promise} p
- * @return {Promise} The result of calling `p.then(onSuccess)`
+ * @return {Promise} The result of calling `p.andThen(onSuccess)`
```
Comment (CrossEye) [inline source/andThen.js]: Oops.  All the other `then`s were correctly changed to `andThen`s.  But this one shouldn't be.

**Comment by CrossEye** [comment]
:herb:

I'm all for this.  I would like to be able to keep the minimal `Promise` support we recently added, and leave them alone thereafter.  This bug was just a distraction... and one more reason to hate Promises!

**Comment by Bradcomp** [comment]
I am :expressionless: on this one. I think it’s good to get it fixed right away though, and this is a good way to do that. Thanks @tmcw!

**Comment by mbostock** [comment]
Was this intended to be released in 0.26.1, or will it be available in a future release?

It looks like it was intended to be part of 0.26.1, but didn’t quite make it. There are two tags in the [releases](https://github.com/ramda/ramda/releases): [0.26.1](https://github.com/ramda/ramda/releases/tag/0.26.1) which includes this change, and [v0.26.1](https://github.com/ramda/ramda/releases/tag/v0.26.1) which does not, and it looks like it was the latter that was published to npm:

https://unpkg.com/ramda@0.26.1/src/then.js

**Comment by mbostock** [comment]
Thanks, @CrossEye!

**Comment by vukhanhtruong** [comment]
@CrossEye You're still not fixing it. Could you please update it? Thanks.
