### PR TITLE
Fixes equality of neg-zero in _Set

### LINKED ISSUE #1742: R.uniq and -0
```js
R.uniq([-0, -0])
// => [-0, -0]
```

### PR DESCRIPTION
**Pull request by scott-christopher**
Fixes #1742

### CODE REVIEW

**Comment by svozza** [comment]
Ha. Beat me to [it](https://github.com/svozza/ramda/blob/uniq-minus-zero/src/internal/_Set.js).

File: src/internal/_Set.js [hunk 1]
```diff
@@ -37,11 +37,15 @@ module.exports = (function() {
...
-            set._items['-0'] = true;
+        if (item === 0 && 1 / item === -Infinity) {
+          if (set._items['-0'] === true) {
+            return !shouldAdd;
+          } else {
+            if (shouldAdd) {
+              set._items['-0'] = true;
+            }
+            return shouldAdd;
           }
```
Comment (davidchambers) [inline src/internal/_Set.js]: I find the logic above difficult to follow. The `shouldAdd` parameter indicates that this function has two modes. The logic above is confusing because it references this parameter several times. I'd like to see a single branch which reflects the fact that `shouldAdd` is a switch. I suggest something along these lines:

```javascript
var setContainsNegativeZero = set._items['-0'] === true;
if (shouldAdd) {
  return setContainsNegativeZero ? false : (set._items['-0'] = true);
} else {
  return setContainsNegativeZero;
}
```

I would also like to see `{'-0': false}` rather than `{}` as the initial value of `set._items`. This would remove the need for `=== true`, and would indicate—in the constructor—the purpose of the `_items` property.

Comment (scott-christopher) [inline src/internal/_Set.js]: > I find the logic above difficult to follow.

I agree. I think the confusion is particularly caused by the overloaded boolean return value. I've updated the PR such that the function will now just return `true` or `false` based on whether the value previously existed.

> I would also like to see {'-0': false} rather than {} as the initial value of set._items. This would remove the need for === true, and would indicate—in the constructor—the purpose of the _items property.

The original PR had this declared explicitly, though we decided to move them all to the same mechanism for consistency. I can add them all back if desired.

**Comment by davidchambers** [comment]
:deciduous_tree: The changes look great, @scott-christopher!

**Comment by scott-christopher** [comment]
And I think negative zero has become my arch-nemesis.

**Comment by jdalton** [comment]
@scott-christopher 
```js
R.prop(-0, {'-0': 'a'}); 
// => undefined
```

**Comment by scott-christopher** [comment]
Yeah that's not nice either. It will give you the expected response if you pass it a string for the first arg though.
```js
R.prop('-0', {'-0': 'a'}); // "a"
```
It sucks that negative zero exists at all in JS, but I guess it just comes along for the ride by having IEEE-754 floats.

**Comment by davidchambers** [comment]
I'd like `R.prop(-0)` to be a type error as it is in Sanctuary:

```javascript
S.prop(-0);
// ! TypeError: Invalid value
//
//   prop :: Accessible a => String -> a -> b
//                           ^^^^^^
//                             1
//
//   1)  -0 :: Number, FiniteNumber, Integer, ValidNumber
//
//   The value at position 1 is not a member of ‘String’.
```

Failing that, the behaviour of `R.prop` when applied to invalid arguments should remain unspecified.

**Comment by jdalton** [comment]
> Yeah that's not nice either. It will give you the expected response if you pass it a string for the first arg though.

```js
R.sum([-0])
// => 0
```

**Comment by CrossEye** [comment]
The fixes are great.  

I have no issue with this:

```js
R.sum([-0])
// => 0
```

Once you start putting `-0` in an additive context, even if we can imagine an implementation which avoids any addition in certain circumstances, I would actually rather this result.  The alternative, presumably `//=> -0`, might lead to some odd results:

```js
    R.sum(numbers.concat(0)) ≍  R.sum(numbers); // ∀ numbers ∈ [Number]
                                                // Oh, wait, except for numbers = [-0]
```

**Comment by davidchambers** [comment]
Good point, @CrossEye. If I were to :trollface: I'd counter with something like this:

```haskell
forall n :: Number. R.sum([n]) = n
```

Seriously, though, `0` and `-0` are equivalent in the context of addition. The behaviour of `R.sum([-0])` does not concern me.

**Comment by jdalton** [comment]
Sweet.
