### PR TITLE
fix(hasPath): forces hasPath to be safe

### LINKED ISSUE #2738: hasPath is not safe
Would it be possible to make `hasPath` function safe ? It works as a predicate and I'd expect the predicates to be safe.

```js
hasPath(['a', 'b'], null); // throws Error
```
In [ramda-adjunct](https://github.com/char0n/ramda-adjunct/blob/master/src/hasPath.js) we have this function for more that a year, although is has recursive implementation it does the same but it's safe. The tests doesn't reflect what happens if the 2nd argument is not an object: https://github.com/ramda/ramda/blob/master/test/hasPath.js

### PR DESCRIPTION
**Pull request by char0n**
The function now doesn't throw Errors anymore when supplied with non-object.
Also fixes R.has.

Closes #2738

Signed-off-by: Vladimir Gorej <vladimir.gorej@gmail.com>

### CODE REVIEW

File: test/hasPath.js [hunk 1]
```diff
@@ -50,4 +59,16 @@ describe('hasPath', function() {
   it('returns false for empty path', function() {
     eq(R.hasPath([], obj), false);
   });
+
+  it('tests paths on non-objects', function() {
```
Comment (CrossEye) [inline test/hasPath.js]: perhaps `it('returns false for non-objects', ...)`

'tests' is very non-specific.

File: test/has.js [hunk 2]
```diff
@@ -22,4 +22,15 @@ describe('has', function() {
     eq(R.has('age', bob), false);
   });
 
+  it('tests paths on non-objects', function() {
```
Comment (CrossEye) [inline test/has.js]: I'd like to find better phrasing here, too, although it's harder to come up with something.

File: test/hasPath.js (hunk 1 above)
Comment (char0n) [reply test/hasPath.js]: yeah we can do that, or we can utilize mochas contexts and [gherkin DSL](http://docs.behat.org/en/v2.5/guides/1.gherkin.html)
```js
context('given second argument is a non-object', function() {
  specify('should return false', function() {
    assertions
  });
});
```
@CrossEye let me know if this is something you like. `context` is alias of `describe`, `specify` of `it`. In this case we have a top level `describe`, we have inner `context` inside `describe` and `specify` inside it.

Comment (CrossEye) [reply test/hasPath.js]: I was only worried about the actual text of the test.  This reads fine to me, but I don't have any real preference between nested `describe`s and this `context`.

**Comment by char0n** [comment]
@CrossEye addressed code review comments.

**Comment by CrossEye** [comment]
This LGTM.  :herb:

Any other comments?  @ramda/core?

**Comment by Bradcomp** [comment]
:bowtie:

**Comment by CrossEye** [comment]
Thanks, @char0n !
