### PR TITLE
Retain arity in cond

### LINKED ISSUE #1570: cond reports wrong arity
```js
R.cond([[R.propEq("a", "b")]]).length; // 0
```

### PR DESCRIPTION
**Pull request by asaf-romano**
Closes #1570

### CODE REVIEW

File: src/cond.js [hunk 1]
```diff
@@ -28,7 +30,9 @@ var _curry1 = require('./internal/_curry1');
  *      fn(100); //=> 'water boils at 100°C'
  */
 module.exports = _curry1(function cond(pairs) {
-  return function() {
+  var arity = pairs.length ?
+    Math.max.apply(Math, map(function(pair) { return pair[0].length; }, pairs)) : 0;
```
Comment (davidchambers) [inline src/cond.js]: We could express this as a fold to obviate the need for the `pairs.length` check.

Comment (asaf-romano) [inline src/cond.js]: ``reduce(function(accum, pair) { return Math.max(accum, pair[0].length); }, 0, pairs)``?

Comment (davidchambers) [inline src/cond.js]: Yes, or this:

```javascript
reduce(max,
       0,
       map(function(pair) { return pair[0].length; }, pairs))
```

**Comment by asaf-romano** [comment]
Heh, one of these days I'll figure out to what extent public api could/should be used. Because outside of ramda I'd go ahead and also do ``pipe(head, length)``.

File: src/cond.js (hunk 1 above)
Comment (asaf-romano) [inline src/cond.js]: Heh, one of these days I'll figure out to what extent public api could/should be used. Because outside of ramda I'd go ahead and also do pipe(head, length).

Comment (davidchambers) [inline src/cond.js]: I copied the lambda from your code above. ;)

Comment (asaf-romano) [inline src/cond.js]: I was referring to the use of both map and reduce, which implies two passes over the same array. I'm fine with that, of course, but as I understand things, the code in src/ looks the way it does because it tries to be as efficient as possible.

Comment (CrossEye) [inline src/cond.js]: >  [A]s I understand things, the code in src/ looks the way it does because it tries to be as efficient as possible.

Yes, but it's a balancing act.  We don't have it all figured out, and every new commit changes the balance a bit.

Comment (asaf-romano) [inline src/cond.js]: I'll go with David's suggested (iterate twice) because in-practice this code never runs (successfully) for arity > 9.

**Comment by davidchambers** [comment]
:deciduous_tree:

**Comment by CrossEye** [comment]
Thank you.  A nice fix!
